### ISSUE TITLE
Capitalize plane keys in Tfs class 

### ISSUE THREAD

**Issue by lmalina** [pylhc/tfs#47]
To improve consistency among our packages capitalize the plane keys for "planed" data frames, i.e. ```("X", "Y")``` instead of  ```("x", "y")```.
Requires change of ```_define_property_two_planes(args, kwargs)```.

**Comment by JoschD** [comment]
Not in the file, names, right?

@lmalina

**Comment by fsoubelet** [comment]
**Small write-up here so that it's always clear:**

When a TfsCollection includes two planes, the attributes are appended with the plane keys (so we get, say, `BET_x`).

Previously the `collection` module implements this with a lowercase plane key (as in the example above). This issue is about respecting the `pylhc` convention of having this key capitalized (above example becomes `BET_X`).

The chosen implementation uses `.lower()` in the `__getitem__` and `__setitem__` methods of the `_TwoPlanes` class. This way, internally the attributes are stored with a lowercase key, but when accessing them both lowercase and capitalized keys are accepted.

This is behavior is now also tested in `test_collection.py`.

> Not in the file, names, right?

This was my mistake.
Convention for the file names across `pylhc` is still to have the plane key as lowercase.

@JoschD @lmalina please confirm this is correct.
